### ISSUE TITLE
if scroll.enabled===true, then Calendar won't initially show the month of shownDate

### ISSUE THREAD

**Issue by justingrant** [Adphorus/react-date-range#190]
If I set the Calendar component (react-date-range@1.0.0-alpha4) to use infinite scroll, then the month shown in the calendar when the page is loaded isn't the month of the shownDate as I'd expect. Instead, the selected month is set to the month of the maxDate.  If I remove the `scroll` prop, then the expected month is shown.  

Am I doing something wrong?  Or is this a bug in react-date-range's infinite scroll implementation?

Repro code:

```
import React, { Component} from 'react';
import 'react-date-range/dist/styles.css'; // main style file
import 'react-date-range/dist/theme/default.css'; // theme css file
import { Calendar } from 'react-date-range';
import { addMonths } from 'date-fns';
 
class MyCalendar extends Component {
  state = {
    date: new Date(Date.now()),
  }

  handleSelect = date => {
    this.setState({date});
  }

  render() {
    return (
      <Calendar
        minDate={new Date (2018, 1, 1)}
        maxDate={addMonths(new Date(Date.now()), 24)}
        shownDate={this.state.date}
        onChange={this.handleSelect}
        scroll={{enabled: true}}
      />
    )
  }
}

export default MyCalendar;

```

**Comment by mkg0** [comment]
@justingrant should be fixed in `alpha5` release ^^

**Comment by GustavoHGS** [comment]
Is anyone still having this issue on version 1.0.0-beta for DateRangePicker?

**Comment by mahesha-perpetualny** [comment]
@GustavoHGS yes i am facing the same issue
