### ISSUE TITLE
Change Early and continuous in DateRange

### ISSUE THREAD

**Issue by altrang** [Adphorus/react-date-range#274]
## Subject of the issue
Is there a way to change Early and Continuous placeholder in DateRange component?
 
thanks a lot

**Comment by onurkerimov** [comment]
This issue is resolved in the latest release (1.1.0). I'm closing this.

**Comment by Mayurkumawat012** [comment]
I still can't change "Early" and "Continuous" text. 
Please help me out.

**Comment by Cauen** [comment]
@Mayurkumawat012 
change following props:

startDatePlaceholder
endDatePlaceholder

**Comment by sachin-vaishnav** [comment]
> startDatePlaceholder

this is perfectly work, thanks
