### ISSUE TITLE
Module parse failed

### ISSUE THREAD

**Issue by christianto88** [Adphorus/react-date-range#348]
## Subject of the issue
It gives error when trying to npm start . 
![image](https://user-images.githubusercontent.com/28486790/75212780-89768180-57ba-11ea-809f-aeba5d28d0bd.png)

 
## [BUG] Bug Reproduce Steps
Tell us how to reproduce this issue.
Error when npm start
## Environment
Package Version: v1.0.1
React version: v16.8.6
Node version: v12.16.1
Browser: Chrome

**Comment by onurkerimov** [comment]
Hi, thanks for pointing out. We also encountered this problem yesterday. In the latest fix on npm (v1.0.3), It should be solved. Can you confirm that the last version solves this issue? 

The problem was about targeted Node versions in Babel configuration file, and it has been changed to cover a broader set of versions.

**Comment by outermedia-kha** [comment]
the problem still exists.

Latest package version from npm: 1.0.3
react: 16.10.2
node: 12.16.1

> ERROR in ./node_modules/react-date-range/dist/components/Calendar/index.js
Module not found: Error: Can't resolve 'date-fns/locale/en-US' in '/.../node_modules/react-date-range/dist/components/Calendar'

**Comment by onurkerimov** [comment]
You need to install `date-fns` in your node_modules. As of the version 1.0.0,  this module expects `date-fns` as a peerDependency. Just run `npm install date-fns` in your project folder and it should be OK. 

You can use this sandbox as an example:
https://codesandbox.io/s/react-date-range-example-bqksq
